### ISSUE TITLE
Trimming long lines

### ISSUE THREAD

**Issue by Crassirostris** [fluent/fluentd#1318]
Currently, in K8S we sometimes experience problems with too long lines: https://github.com/kubernetes/kubernetes/issues/37010

One of the possible solutions would be to trim the lines to be under, say, 100KB. But I wasn't able to find any information regarding this problem. Is it possible in fluentd right now?

It would be also really great to achieve this using only build-in plugins.

We're currently using fluentd 0.12, [Dockerfile](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-image/Dockerfile)

**Comment by repeatedly** [comment]
> But I wasn't able to find any information regarding this problem.

Because you are first person for such requirement.
In addition, fluentd hard to judge which point is safe to prevent garbage line.

> It would be also really great to achieve this using only build-in plugins.

if one field is larger than 100KB, `record_transformer` filter can achieve it like below:

```rb
<filter pattern>
  @type record_transformer
  enable_ruby true
  auto_typecast true

  <record>
    foo ${record["large_field"][0..10]}
  </record>
</filter>
```

But this is not efficient. If you can write your own parser, it is better for reducing additional text processing and memory allocation.

**Comment by Crassirostris** [comment]
@repeatedly OK, thanks!

Closing the issue, you completely answered my question :)
