### ISSUE TITLE
fluentd auto restart with process finished code=6

### ISSUE THREAD

**Issue by pensz** [fluent/fluentd#139]
I use fluentd as log collection service. At the beginning, I just write log received to hdfs. It works fine and stable. But when I wanna copy received log and forward to another fluentd. It becomes unstable.

```
...
2013-05-30 13:36:21 +0800 [info]: process finished code=6
...
2013-05-30 13:40:03 +0800 [info]: process finished code=6
...
2013-05-30 13:41:11 +0800 [info]: process finished code=6
2013-05-30 13:41:11 +0800 [info]: starting fluentd-0.10.33
2013-05-30 13:41:11 +0800 [info]: reading config file path=" .... "
2013-05-30 13:41:11 +0800 [info]: using configuration file
...
```

It seems that fluentd auto restart in several minutes. 
Here is my configuration with fluentd 0.10.33.

Thxs for any advice!

```
  <source>
    type forward
    port 24225
    bind 0.0.0.0
  </source>
  <match applog.**>
    type copy
    <store>
      type forest
      subtype webhdfs
      remove_prefix applog
      <template>
        host 10.10.1.1
        port 50070
        username hadoop
        path /applog/${tag}/%Y%m%d/%H.log
        flush_interval 60s
        read_timeout 100
        field_separator TAB
        output_include_time false
        output_include_tag false
        output_data_type attr:all
      </template>
      <case dw.**>
        path /applog/${tag}/%Y%m%d/%H_%M.log
        flush_interval 30s
      </case>
    </store>

    # copy log and forward to another fluentd
    <store>
      type forward
      flush_interval 1s
      heartbeat_interval 60s
      <server>
        name app10-001
        host 10.10.3.1
        port 24227
        weight 100
      </server>
    </store>

  </match>

```

**Comment by igorpeshansky** [comment]
I am consistently hitting this issue (`process finished code=6`). This is probably caused by something I'm doing in my [plugin code](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/tree/grpc) (add `use_grpc true` to the plugin config to turn on). However, when I run fluentd with the same config outside of the service framework (even with --daemon), it does not crash. The crashes only happen while run via init/systemd.
Please let me know how I can help debug this.

**Comment by repeatedly** [comment]
Please paste your fluentd / plugin versions and configuation to reproduce the problem.

**Comment by igorpeshansky** [comment]
Thank you for responding. Here are the fluentd and plugin versions:
```
fluentd (0.12.20)
fluent-plugin-google-cloud (0.5.3.grpc.alpha.1)
```
Unfortunately, the easiest way to reproduce would be to run https://dl.google.com/cloudagents/install-logging-agent.sh on a Google Compute Engine VM, then `/opt/google-fluentd/embedded/bin/gem install --pre fluent-plugin-google-cloud`, then edit `/etc/google-fluentd/google-fluentd.conf` and add `use_grpc true` right under `type google_cloud`. Running the plugin requires certain authorization that can only be obtained from a Google Cloud project.
I'd be happy to give you ssh access to a running VM that demonstrates this issue.

**Comment by repeatedly** [comment]
@igorpeshansky 

> I'd be happy to give you ssh access to a running VM that demonstrates this issue.

So this problem is hard to reproduce on vanilla Ubuntu or CentOS?
If so, I want to use your environment for debugging.

**Comment by igorpeshansky** [comment]
Thank you for responding.
The problem for me appears only when using the Google Cloud output plugin with my latest changes enabled. I suspect the code is doing something nasty, causing fluentd/ruby to quit, but there is no indication of what that is. It may be possible to reproduce outside of Google Cloud, but it would be difficult to obtain the necessary credentials that would work on a standalone instance. Easier to use the existing VM.
Do you have a Google account? If so, please email it to me off-thread (to igorp@google.com or my GitHub email) and I'll add you to the project and respond with connection instructions. Otherwise, please email me an ssh key and I'll add it to the instance.
