### ISSUE TITLE
in_tail  loses data when rotating big files - Option to having "infinite" rotate_wait?

### ISSUE THREAD

**Issue by ofirnn** [fluent/fluentd#1428]
When a big file is getting into **in_tail** - and logrotate is running (with delaycompress - old file is still exists with its format) - a data-loss can occur if rotate_wait isn't long enough.

The practice is to set rotate_wait into a longer value -> isn't there another option like wait until reaching the EOF in posfile - before letting the old file being dropped from the monitored files list?

**Comment by repeatedly** [comment]
> like wait until reaching the EOF

This is difficult problem because EOF is not real EOF in streaming manner.

https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_tail.rb#L633

in_tail stops reading file when gets EOF. If the in_tail is faster than log written speed, in_tail also gets EOF before next write. So we can't use EOF for `inifite` wait.

**Comment by repeatedly** [comment]
Temporarily closed.
If someone has good idea to handle the case, please reopen it.
