### ISSUE TITLE
Filter plugin which the name suffix is '_filter' is not found in v0.14

### ISSUE THREAD

**Issue by cubicdaiya** [fluent/fluentd#1445]
After upgrading from v0.12.7 to v0.14.11, fluentd could not find our some filter plugin on startup.
Its plugin name has the suffix '_filter'. In this case, latest fluentd can not find plugin. 

```
error_class=Fluent::ConfigError error="Unknown filter plugin 'some_filter'. Run 'gem search -rd fluent-plugin' to find plugins"
```

On the other hand, fluentd-0.12.7 could find plugin of the name of 'some_filter'.

The followings are the configuration and filter plugin code for reproducing this problem.

## configuration (/etc/td-agent/td-agent.conf)

```xml
<filter some_log>
  type some_filter
</filter>

# abbreviated
```

## plugin code (/etc/td-agent/plugin/filter_some.rb)

```ruby
module Fluent
  class SomeFilter < Filter
    Fluent::Plugin.register_filter('some_filter', self)
    def filter(tag, time, record)
      record
    end
  end
end
```

## other environment informations

* OS: CentOS Linux release 7.3.1611 (x86_64)
* td-agent package version: 2.3.4-0.el7

## workaround

Now I have verified that fluentd-v0.14.11 could find `/etc/td-agent/plugin/filter_some.rb` if configuration and plugin code are modified like below. ( Eliminate the suffix '_filter' in plugin name)

### modified configuration

```xml
<filter some_log>
  type some
</filter>
```

### modified plgin code

```ruby
module Fluent
  class SomeFilter < Filter
    Fluent::Plugin.register_filter('some', self)
    def filter(tag, time, record)
      record
    end
  end
end
```

Though I could not find explanation about this in [updating guide](http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12), is this the expected behavior?

**Comment by repeatedly** [comment]
It is expected behaviour.
In previous versions, fluentd loads all ruby files in `/etc/fluent/plugin`(`/etc/td-agent/plugin` in td-agent).
This loads unnecessary files and it may cause unexpected plugin overload.
So we fixed this rough loading mechanizm.

In plugin development article, plugin path should be `<TYPE>_<NAME>.rb` and
each plugin section mentions `Fluent::Plugin.register_xxx('NAME', self)` in the code.
So we assume this change doesn't break existing deployment.
Hmm... hard to judge old buggy mechanizm keep or not...

**Comment by repeatedly** [comment]
Renaming file to proper plugin format fixes the problem.
If you think v0.14 keep old behaviour, please reopen this issue.
