### ISSUE TITLE
Getting error while restarting/starting td-agent in ubuntu

### ISSUE THREAD

**Issue by neeravarora** [fluent/fluentd#1519]
Iam getting the following error if i try to start or restart the td-agent .

_Starting td-agent (via systemctl): td-agent.serviceJob for td-agent.service failed because the control process exited with error code. See "systemctl status td-agent.service" and "journalctl -xe" for details._

**Comment by repeatedly** [comment]
From slack, you seems to resolve the problem.

**Comment by neeravarora** [comment]
Ok cool

**Comment by VenkatNarayanaYarava** [comment]
Iam getting the following error if i try to start or restart the td-agent .

_Starting td-agent (via systemctl): td-agent.serviceJob for td-agent.service failed because the control process exited with error code. See "systemctl status td-agent.service" and "Feb 13 17:37:57 efk systemd[1]: Starting td-agent: Fluentd based data collector for Treasure Data...
-- Subject: Unit td-agent.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit td-agent.service has begun starting up.
Feb 13 17:37:57 efk systemd[18670]: Failed at step EXEC spawning /opt/td-agent/embedded/bin/fluentd: No such file or directory
-- Subject: Process /opt/td-agent/embedded/bin/fluentd could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- The process /opt/td-agent/embedded/bin/fluentd could not be executed and failed.
--
-- The error number returned by this process is 2.
Feb 13 17:37:57 efk systemd[1]: td-agent.service: control process exited, code=exited status=203
Feb 13 17:37:57 efk systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
-- Subject: Unit td-agent.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit td-agent.service has failed.
--
-- The result is failed.
Feb 13 17:37:57 efk systemd[1]: Unit td-agent.service entered failed state.
Feb 13 17:37:57 efk systemd[1]: td-agent.service failed.
Feb 13 17:37:57 efk systemd[1]: td-agent.service holdoff time over, scheduling restart.
Feb 13 17:37:57 efk systemd[1]: Stopped td-agent: Fluentd based data collector for Treasure Data.
-- Subject: Unit td-agent.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit td-agent.service has finished shutting down.
Feb 13 17:37:57 efk systemd[1]: start request repeated too quickly for td-agent.service
Feb 13 17:37:57 efk systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
-- Subject: Unit td-agent.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit td-agent.service has failed.
--
-- The result is failed.
Feb 13 17:37:57 efk systemd[1]: Unit td-agent.service entered failed state.
Feb 13 17:37:57 efk systemd[1]: td-agent.service failed.
" for details._




This is the my output of journalctl -xe
