### ISSUE TITLE
Problem with file output plugin [fluentd:1.2.6]

### ISSUE THREAD

**Issue by Renz2018** [fluent/fluentd#2166]
- fluentd:1.2.6
- docker:FROM fluent/fluentd:v1.2.6-debian-onbuild

> <match test.app.test>
    @type file
    path /fluentd/log/apps/test/app/test/tmp
    compress gzip
    <buffer>
      timekey 1d
      timekey_use_utc true
      timekey_wait 10m
    </buffer>
</match>

I will find a file in /fluentd/log/apps/test/app/test/tmp/buffer.b579f53bc3968f0100742985bd0d2a1c9.log,
But  when i tail -f  /fluentd/log/apps/test/app/test/tmp/buffer.b579f53bc3968f0100742985bd0d2a1c9.log ,    It's odd ,   It's not stream log ,  but a lots of message appear suddenly!!
I want it's behavior normal,  log appear one after one, not a  lot of log appear together, how could  I config?
Thanks for the help.

**Comment by repeatedly** [comment]
It depends on your input side.
Fluentd's data stream is based on micro batch approach so some plugins emit the number of events at once.
For example, in_tail emits 1000 events with one line logs by default.

https://github.com/fluent/fluentd/blob/2829b9c52b5924320be90d82ea445e2977fe8c4a/lib/fluent/plugin/in_tail.rb#L76

> log appear one after one

This is not normal in log forwarding because it is not efficient...

> how could I config

If your used input has a configuration for the number of emitted log, you can change it.
