### ISSUE TITLE
keepalive property

### ISSUE THREAD

**Issue by dpgaspar** [fluent/fluentd#2188]
Hi,

We have a deployment with fluentd client agents forwarding to fluentd aggregators that handle routing and some parsing. The fluentd aggregators are behind an AWS ELB with ASG. So on higher load we spawn automatically new instances. Yet the clients tend to stay on the same instance, so load balancing is far from perfect.

We way we use to improve load balance is to use the 'keepalive' tls property present on the 0.12 version

The problem is that it seems this property is not present on 1.2.6. Do you have any plans to bring it back?

Do you propose a different architecture for better load balancing and still have scale up and down feature?

OS
- Amazon Linux, Ubuntu, CentOS

**Comment by repeatedly** [comment]
Yeah, it is now TODO task.
We will import keepalive feature from secure-forward or keep-forward.

**Comment by dpgaspar** [comment]
Hi,

Do you have any ETA for this feature?

Thank you

**Comment by luhn** [comment]
Based on the observed behavior of fluentd in my environment and reading through the out_forward code, it appears that fluentd only keeps a connection open long enough to write a given chunk and then immediately closed.  Am I understanding this correctly?

@dpgaspar, this behavior should give the desired result for load balancing.

However I think keepalive is important, especially when using TLS, because establishing a new TLS connection is slow and expensive.
