### ISSUE TITLE
Transport TLS not starting listener

### ISSUE THREAD

**Issue by udf2457** [fluent/fluentd#2241]
fluentd 1.2.6 (Fluentd installed via CentOS Repo)
CentOS Linux release 7.6.1810 (Core) 

I believe the following config should be correct, however although `fluentd` starts without errors, no listener is opened on 24228

The cert being used is signed by a commercial CA.  cert_path is the signed certificate with the intermediate and root certs chained (i.e. appended for those not familiar with the 'chained' concept )

```
<source>
  @type forward
  @id input_secure_forward
  bind 0.0.0.0
  port port 24228
  <transport tls>
    cert_path /etc/td-agent/certs/foobar.pem
    private_key_path /etc/td-agent/certs/foobar.key
    private_key_passphrase barfoo
  </transport>
</source>
```

**Comment by udf2457** [comment]
@repeatedly oops !  Thank you for spotting that !

Will `<transport tls>` work with `@type http` ?

**Comment by udf2457** [comment]
```
<match debug.**>
  @type stdout
  @id output_stdout
</match>
```

Does not seem to be matching:

`echo '{"message":"testing the SSL forwarding"}'  | /opt/td-agent/embedded/bin/fluent-cat --port 24228  --json debug.log`

Is this as expected ?

**Comment by repeatedly** [comment]
> Will <transport tls> work with @type http ?

Not supported yet. To support TLS in `in_http`, we need to rewrite `in_http` plugin with server plugin helper.

**Comment by EvertonSA** [comment]
Hi,
I'm having a similar situation where I have correctly configured TLS certs and I can confirm that the source is working fine:
with `sudo tcpdump -i eth0 tcp port 24228 -X -s 0 -nn` I see the following:

06:28:47.838623 IP 10.0.0.16.53324 > 10.0.0.24.24228: Flags [R], seq 925355541, win 0, length 0
        0x0000:  4500 0028 1f38 4000 4006 0771 0a00 0010  E..(.8@.@..q....
        0x0010:  0a00 0018 d04c 5ea4 3727 ce15 0000 0000  .....L^.7'......
        0x0020:  5004 0000 678b 0000                      P...g...

With `netstat -tulpn | grep 24228` I have: 
tcp        0      0 0.0.0.0:24228           0.0.0.0:*               LISTEN      44445/ruby
udp        0      0 0.0.0.0:24228           0.0.0.0:*                           44445/ruby

I'm debugging using stdout: 
```
<match *.**>
  @type stdout
</match>
```

My source config looks like this:
```
<source>
  @type forward

  port 24228

  <transport tls>
    version TLSv1_2
    ciphers ALL:!aNULL:!eNULL:!SSLv2
    insecure false
    ca_cert_path              #NOT DISPLAYED FOR SECURITY REASONS
    ca_private_key_path       #NOT DISPLAYED FOR SECURITY REASONS
  </transport>
</source>
```
weirdly enough, I see the following when `tail -f /var/log/td-agent/td-agent.log`

2019-03-20 05:56:50 +0100 [info]: adding source type="forward"
2019-03-20 05:56:50 +0100 [info]: adding source type="syslog"
2019-03-20 05:56:50 +0100 [info]: #0 starting fluentd worker pid=35680 ppid=35675 worker=0
2019-03-20 05:56:50 +0100 [info]: #0 listening syslog socket on 0.0.0.0:42185 with udp
2019-03-20 05:56:50 +0100 [info]: #0 listening port port=24228 bind="0.0.0.0"
2019-03-20 05:56:51 +0100 [info]: #0 fluentd worker is now running worker=0

I apologize for not going deeper into this, but I see `port port=24228` at the logs, and this is pretty weird since my config looks pretty much simple.

**Comment by udf2457** [comment]
Dear Mr @github-actions .... ignoring the problem won't make it go away. ;-)
