### ISSUE TITLE
out_foward with keepalive and shared_key don't work together

### ISSUE THREAD

**Issue by luhn** [fluent/fluentd#2451]
When using out_forward with keepalive and shared_key, no data is sent.  There is no error.  Everything works as expected when either shared_key or keepalive is disabled.

I've created a docker-compose which reproduces the issue:  https://gist.github.com/luhn/af36a17b46a3eb7640ccb7c5bacea9bc

**Comment by repeatedly** [comment]
Hmm... I can't reproduce this problem on my environment.
Did you see the error in fluentd log?

**Comment by luhn** [comment]
There is no error that I can see. 

You should be seeing load averages show up after a few seconds in the dst container. Nothing ever comes across. 

— Theron

**Comment by repeatedly** [comment]
Ah wait. My mistake. I forgot to rebuild src image with `keepalive true`.
This problem is reproduced with docker-compose.
In addition, I tested this config without docker-compose and it worked.
The weird thing is setup socket is same between `keepalive false` and `keepalive true`.
Need to investigate.

**Comment by ganmacs** [comment]
Thank you for reporting! @luhn .
I confirmed this is a keepalive bug. #2456 should fix this issue.

**Comment by luhn** [comment]
Thanks!
