### ISSUE TITLE
NATS jetstream output plugin

### ISSUE THREAD

**Issue by Mostafakhedri** [fluent/fluentd#3495]
### Is your feature request related to a problem? Please describe.

Hi, I have some problem with fluentd output plugins for nats. Actually i want to use fluentd as a publisher for NATS jetstream, but it seems that we don’t have any nats output plugin in fluentd. What can i do for this problem?

### Describe the solution you'd like

Can we have a NATs Jetstream output plugin in fluentd? That's how we can use Fluentd as publisher for NATs

### Describe alternatives you've considered

Something like that:
<match fluent**>
    @type natsJetstream
    brokers <broker1_host>:<broker1_port>,<broker2_host>:<broker2_port>
    user nats
    password nats
    subjects fluent.>,fluent2.>
    ssl true/false
    .
    .
    .
  </match>

**Comment by kenhys** [comment]
I'm not tested yet, but it seems there is a plugin. Does it work for you?

https://github.com/hc-chien/fluent-plugin-nats-streaming

**Comment by Mostafakhedri** [comment]
Hi, thanks alot, i'll check it

**Comment by kenhys** [comment]
I'm not sure but, It may be caused by periodic `sleep (5)` intervals.
https://github.com/hc-chien/fluent-plugin-nats-streaming/blob/master/lib/fluent/plugin/in_nats-streaming.rb#L127
https://github.com/hc-chien/fluent-plugin-nats-streaming/blob/master/lib/fluent/plugin/in_nats-streaming.rb#L79

Anyway, I'll recommend you to raise it as an issue at https://github.com/hc-chien/fluent-plugin-nats-streaming/, because it has nothing to do with fluentd itself.
