### ISSUE TITLE
Time format differs from Linux output

### ISSUE THREAD

**Issue by Diablo2050** [fluent/fluentd#3564]
### Describe the bug

Time format in `match` is different than using `date` on Linux machine (Ubuntu 20.04)

### To Reproduce

Configure a forwarder and use this block on the receiver

`<source>
  @type forward
  port 24224
  bind 0.0.0.0
  @id input_forward
</source>

<match pm2.app>
    @type file
    path /logs/${tag}/%Y%m%d%H
    <buffer tag,time>
#      timekey 15m
#      timekey_use_utc true
#      timekey_wait 5m
       flush_mode interval
       flush_interval 1m
       flush_at_shutdown true
    </buffer>
    append false
</match>`

### Expected behavior

using this command `date +%Y_%m_%d_%H` outputs `2021_11_28_15` but using `%Y%m%d%H` in fluentd configuration file generates `2021112800_0.log`.
The expected file name is `2021112815_0.log`.

### Your Environment

```markdown
- Fluentd version: 1.13.3
- TD Agent version: 4.2.0
- Operating system: Ubuntu 20.04.3 LTS
- Kernel version: 5.4.0-73-generic
```

### Your Configuration

```apache
`<source>
  @type forward
  port 24224
  bind 0.0.0.0
  @id input_forward
</source>

<match pm2.app>
    @type file
    path /logs/${tag}/%Y%m%d%H
    <buffer tag,time>
#      timekey 15m
#      timekey_use_utc true
#      timekey_wait 5m
       flush_mode interval
       flush_interval 1m
       flush_at_shutdown true
    </buffer>
    append false
</match>`
```

### Your Error Log

```shell
No error log.
```

**Comment by ashie** [comment]
Default `timekey` of `out_file` plugin is `60 * 60 * 24` [sec]:

https://github.com/fluent/fluentd/blob/438a82aead488a86180cd484bbc4e7e344a9032b/lib/fluent/plugin/out_file.rb#L39

https://github.com/fluent/fluentd/blob/438a82aead488a86180cd484bbc4e7e344a9032b/lib/fluent/plugin/out_file.rb#L64

So that logs are splitted per day.
`%H` is truncated to `00` due to this.

Above thing doesn't seem documented in https://docs.fluentd.org/output/file
We should describe it.

**Comment by ashie** [comment]
e.g.) If you set `timekey 3600`, `%H` will be correctly formatted.

**Comment by ashie** [comment]
I've added it to the document: https://docs.fluentd.org/output/file#timekey
