### ISSUE TITLE
Enable CORS on HTTP Input plugin

### ISSUE THREAD

**Issue by shacharz** [fluent/fluentd#426]
Is it possible to enable cross origin resource sharing with the http input plugin, so a browser can report directly to a server different from the server hosting the web page?

**Comment by gma-git-admin** [comment]
Am using in_http to take in the json log data from my angular app. Have added the angular app url in the list for cors_allow_origins in the conf file. The source configuration is reproduced here for reference:

<source>
  @type http
  port 8282
  bind 0.0.0.0
  body_size_limit 32m
  keepalive_timeout 10s
  add_remote_addr true
  ##add_http_headers true
  cors_allow_origins ["http://dev.myapp.com"]
  format json
</source>


But, I still get the HTTP 400 bad request error as given below:

XMLHttpRequest cannot load http://dev.myapp:8282/app.RouteChange. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.  Origin 'http://dev.myapp.com' is therefore not allowed access. The response had HTTP status code 400.

Am I missing some important configuration or doing something wrong here?

**Comment by adonishi** [comment]
@gma-git-admin 
I came across the same problem, and find out http-input plugin only support preflight less CORS.
```javascript
    var xhr = new XMLHttpRequest();
    xhr.open('POST', url);
    // xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.send(json);
```
code above works fine with http-input plugin, since browser do not send preflight request.
but uncomment 'Content-Type' line will fail, because browser will send preflight request before actual json POST request. and preflight request always fail with '400 bad request'.
