### ISSUE TITLE
Failed to parse SYSLOG message data

### ISSUE THREAD

**Issue by afza1** [fluent/fluentd#4277]
### Describe the bug

Using [https://docs.cloudfoundry.org/devguide/services/fluentd.html](https://docs.cloudfoundry.org/devguide/services/fluentd.html) to configure CloudFoudry Logdrain to get logs to FluentD.

However, the parser is keep throwing this following error.
FluentD parser is showing message 
`2023-08-21 13:32:14 -0700 [warn]: #0 failed to parse message data="..."`

### To Reproduce

1. CloudFoundry configured to send logs to syslog://URL:PORT
2. Copy config to `td-agent.conf`
3. Run the agent and see logs in console.

### Expected behavior

parse key value pair of the syslog.

### Your Environment

```markdown
- Fluentd version: fluentd 1.16.1
- TD Agent version: td-agent 4.5.0 
- Operating system: Windows 11
- Kernel version:
```

### Your Configuration

```apache
<source>
  @type syslog
  port 8080
  bind 0.0.0.0
  tag cf.app
  <transport tcp>
  </transport>
  <parse>
    message_format rfc5424
  </parse>
</source>


<match cf.app>
  @type stdout
</match>
```

### Your Error Log

```shell
2023-08-21 13:32:14 -0700 [warn]: #0 failed to parse message data="685 <14>1 2023-08-21T20:32:01.74431+00:00 ORG_NAME.SPACE_NAME.APP_NAME d7a37367-62cc-4140-9f98-d87952f7f18b [APP/PROC/WEB/0] - [tags@47450 app_id=\"d7a33367-52cc-1140-9g98-d88852f7f18b\" app_name=\"APP_NAME\" deployment=\"cf-release\" index=\"76d09082-cdbf-401a-9e17-5ca59bcdbe5e\" instance_id=\"0\" ip=\"10.10.10.10\" job=\"cell\" organization_id=\"4e1a1098-1ce4-4120-a431-8b94a33ff2fc\" organization_name=\"ORG_NAME\" origin=\"rep\" process_id=\"d7a37367-62cc-4140-9f98-d87952f7f18b\" process_instance_id=\"318b2e58-e2a3-4e66-4df5-fcc9\" process_type=\"web\" source_id=\"d7a37367-62cc-4140-9f98-d87952f7f18b\" source_type=\"APP/PROC/WEB\" space_id=\"fcfe9299-f102-4b3a-b4eb-5040ef6fffd4\" space_name=\"SPACE_NAME\"] Landing Page Loaded."
```

**Comment by kenhys** [comment]
incoming event data is not compatible with rfc5424.
In such a case, you need to use custom parser or regex instead.

**Comment by darknetehf** [comment]
I have the same issue when sending syslog events to Fluentd (using syslog-ng).
Sending events over TCP (unencrypted) works fine, but parsing errors occur when using TLS.

If you look at your sample:
`685 <14>1 2023-08-21T20:32:01.74431+00:00 ORG_NAME.SPACE_NAME.APP_NAME`
There is a leading number (685), that causes the parsing error. It is not part of the original syslog message data, but was added by middleware.

The root cause is **octet counting framing**, that happens with TLS. This is described here: https://nxlog.co/news-and-blog/posts/syslog-forwarding-over-tls

One possible fix is to add the `frame_type octet_count` directive in your Fluentd configuration.
If you look at the Cloudfoundry doc, they mention this. But it's missing from your config, and that makes a difference.

Below are two Fluentd configurations that work for me:
- TCP (unencrypted) 
- TLS (encrypted)

### Receiving syslog over port 5140 - unencrypted

```
<source>
  @type syslog
  @label @FORWARD
  tag syslog
  bind 0.0.0.0
  port 5140
  <transport tcp>
  </transport>
  <parse>
    message_format auto
  </parse>
</source>
```

### Receiving syslog over port 6514 - encrypted

```
<source>
  @type syslog
  @label @FORWARD
  tag syslog
  bind 0.0.0.0
  port 6514
  frame_type octet_count
  <transport tls>
    ca_path ...
    cert_path ...
    private_key_path ...
  </transport>
  <parse>
    message_format auto
  </parse>
</source>
```
