### ISSUE TITLE
Duplicate logs getting created on Opensearch through fluentd

### ISSUE THREAD

**Issue by SohailLS** [fluent/fluentd#4420]
### Describe the bug

Hi Team,

fluentd is generating logs 5 times on Opensearch.
We have tried implementing below solution with "elasticsearch_genid" and its even able to generate _hash values.... but its not able to remove the duplicates.

https://medium.com/redbox-techblog/tuning-fluentd-retries-avoiding-duplicate-documents-in-elasticsearch-e7cb9630a453.

logs flow is as below
fluentbit -> fluentd -> Opensearch

Earlier we were having only fluent-bit and it was working fine.

After introducing fluentd for multiple log files we started facing the issue.

Please advise.

### To Reproduce

Please use the attached configs for fluent-bit and fluentd to reproduce the issue.

[3ds-fluentbit.txt](https://github.com/fluent/fluentd/files/14435405/3ds-fluentbit.txt)
[td-agent.txt](https://github.com/fluent/fluentd/files/14435437/td-agent.txt)

### Expected behavior

Single logs should get reported on the Opensearch end.

### Your Environment

```markdown
- Fluentd version: 1.16.3
- TD Agent version: 4.5.2
- Operating system: RHEL 8.9
- Kernel version: 4.18.0-513.11.1.el8_9.x86_64
- Fluent-bit version: 2.1.5
```

### Your Configuration

```apache
PFA
```

### Your Error Log

```shell
No error logs.
```

**Comment by SohailLS** [comment]
Requesting for a quick solution.
Most of our deliverables are stuck due to this issue.

**Comment by daipom** [comment]
@SohailLS Sorry for my late response.
Could you please send the issue report to https://github.com/fluent/fluent-plugin-opensearch/issues as well?
Because it looks like the issue of `fluent-plugin-opensearch`.

https://medium.com/redbox-techblog/tuning-fluentd-retries-avoiding-duplicate-documents-in-elasticsearch-e7cb9630a453 says retrying can cause duplication.
The output plugin fails to send data and retries, but Opensearch is actually properly received the data.
This is what is happening in your environment as well, right?

If so, one thing that could be done on the Fluentd itself (not `fluent-plugin-opensearch`) is to disable retries.
(There is a concern, though, that it is not possible to retry data that actually failed to send...)

You can set `retry_max_times 0` to disable retries. (https://docs.fluentd.org/output#control-retrying)

```xml
<match xxx>
  ...
  <buffer>
    retry_max_times 0
  </buffer>
</match>
```

Or, you can also have it sent to a secondary just in case.
(This adjusts the parameters to switch to the secondary from the first retry.)

```xml
<match xxx>
  ...
  <buffer>
    retry_type periodic
    retry_max_times 3
    retry_secondary_threshold 0.1
    retry_randomize false
  </buffer>
  <secondary>
    ...
  </secondary>
</match>
```
