### ISSUE TITLE
flush_interval is not working when huge buffer is accumulated

### ISSUE THREAD

**Issue by deepakmittal** [fluent/fluentd#572]
I have following configuration,

```
<match aggregated.feed>
  type mysql
  host localhost
  database ---
  username ---
  password ----
  flush_interval 20s
  buffer_type file
  num_threads 32
  buffer_path /var/log/td-agent/buffer/realtime.feed.toMysql*.buffer
</match>
```

Everything was working fine till my mysql table was locked for sometime due to some heavy query. So as expected buffer started piling up. But buffer was piling up in same chunk file. New chunk was created only after default size of buffer_chunk_limit (8mb) was reached.
As mentioned in http://docs.fluentd.org/articles/buffer-plugin-overview new chunk should have been created after every flush_interval 20s. 
As multiple chunks are not generated use of 'num_threads' did not have any impact as it enables parallel processing of different chunks. This slowed down buffer clearing after mysql was unlocked.

It seems like flush_interval is not respected once the buffer starts piling up.

**Comment by repeatedly** [comment]
> As mentioned in http://docs.fluentd.org/articles/buffer-plugin-overview new chunk should have been created after every flush_interval 20s. 

Buffer chunk is created after each flush_interval because internal buffers are moved to internal queue.
And if queue is not empty, queue's chunk are flushed immediately. It can be customised by queued_chunk_flush_interval. Default is 1s.

I don't know the detail of your situation.
But if slows down the consumption of buffers, your mysql may lack resources, CPU / Memory or so.
Technically, mysql plugin execute query for each record.
It means if you have 1000 records, mysql plugin issues 1000 queries.
Using bulk load version of mysql plugin may resolve your problem.

**Comment by repeatedly** [comment]
Maybe, the problem is mysql plugin.
If the problem is fluentd itself, please reopen this issue.
