### ISSUE TITLE
package for wheezy 32bit

### ISSUE THREAD

**Issue by dfateyev** [fluent/fluentd#578]
Could you please prepare a "td-agent" package for 32bit Debian Wheezy?
That's a pity that 64bit version is only here but often needed 32bit is missing.
Thanks.

**Comment by repeatedly** [comment]
I assume you mean td-agent.
Sorry, we don't have a plan to release Debian 32bit for now because there are very few Debian 32bit users.
If the users are increased, we can release packages for 32bit environment.

You can build your own td-agent package using this repository: https://github.com/treasure-data/omnibus-td-agent
