### ISSUE TITLE
Enforce 'record' is of type hash, or update the documentation

### ISSUE THREAD

**Issue by mr-salty** [fluent/fluentd#591]
According to the fluent plugin docs at http://docs.fluentd.org/articles/plugin-development 'record' is required to be a Hash object, but this is not enforced inside of fluentd.

If the documentation is correct, then fluentd should enforce this, otherwise the documentation should be updated.

Enforcement may be problematic since it may break existing uses.  For example, see https://github.com/fluent/fluent-logger-python/issues/34 where the python logger emits a string.  Granted, that issue should be fixed independently, but it would be difficult to determine if there are other similar cases.  A gentler approach may be to try to recover from this situation by parsing the string or placing it in record['message']

I noted that there are at least some output plugins that discard anything that is not a hash, i.e. elasticsearch: https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L125

My own plugin (google-cloud) currently throws an exception when this happens.

**Comment by repeatedly** [comment]
> Enforcement may be problematic since it may break existing uses. For example, see fluent/fluent-logger-python#34 where the python logger emits a string.

Hmm... this seems a bug of fluent-logger-python. I will fix it later.
Other clients don't send string record. For example, fluent-logger-ruby validates the record type https://github.com/fluent/fluent-logger-ruby/blob/master/lib/fluent/logger/logger_base.rb#L26 and other statically typed language loggers also support only Hash.

> A gentler approach may be to try to recover from this situation by parsing the string or placing it in record['message']

I assume this problem happens on only in_forward with buggy logger situation so making hash record with string record is not needed. In addition, automatic convert is not good for some users. For example, if an user uses RDBMS like output, it may cause a schema mismatch error.

> I noted that there are at least some output plugins that discard anything that is not a hash, i.e. 

This behaviour seems acceptable because output plugin doesn't know how to handle this.
Dumpling invalid record to error / warning may be good.

Other possible solution is dumping invalid records to error / warning log in input plugin. Maybe in_forward.

**Comment by repeatedly** [comment]
fluent-logger-python is fixed.
I close this issue. If you hit similar problem, please reopen this issue.
