### ISSUE TITLE
record_transformer remove_keys: support structured data

### ISSUE THREAD

**Issue by svengau** [fluent/fluentd#649]
Hi, 

It would be nice that `remove_keys` support an array in record_transformer.

Example: remove set-cookie header from an NGinx response:

```
<filter **>
  type record_transformer
  remove_keys res.headers.set-cookie
</filter>
```

Thanks,
Sven

**Comment by sonots** [comment]
remove_keys support an array like (comma separated):

```
remove_keys a,b,c
```

**Comment by svengau** [comment]
Sorry for the misunderstand, I mean for this kind of log: 

```
res {
  headers {
    set-cookie: "xxxxxxxxxx",
    etag: "xxxxxxxx",
    ...
  }
}
```
having the possibility to remove structured data, like set-cookie and etag:
```
remove_keys res.headers.set-cookie,res.headers.etag

**Comment by sonots** [comment]
Let me take a note. I do not think this problem can be solved soon. 

1. Need to determine an official way to express a structured data. Using `.` as a separator means that we need to prohibit `.` for record keys so that we can differentiate `record["a.b"]` and `record["a"]["b"]`, for example. 
  * Prohibiting `.` for record keys breaks backward compatibility
2. Need to add features to transform record structured data (not only remove) side by side.

**Comment by repeatedly** [comment]
Does JSONPath use `.` for separator?

**Comment by llby** [comment]
@repeatedly @sonots 
How abount add `remove_json_keys` at config_param
and use like this

```
remove_json_keys {"message":[{"res":{"headers":{"set-cookie":0}}},{"res":{"headers":{"etag":0}}}]}
```

0 means delete
because json needs value

**Comment by repeatedly** [comment]
Use https://github.com/fluent/fluentd/issues/1578 instead
