### ISSUE TITLE
Advices for fluentd monitoring

### ISSUE THREAD

**Issue by papiveron** [fluent/fluentd#658]
Hi,

I'm making a list of things I can monitor on fluentd. 

I noticed there are two processes, a **supervisor** and a **worker**. For example on my system, this is the **ps** command output :

```
[admin@ip-192-168-101-241]~ ❯❯❯  ps w -C ruby -C td-agent
  PID TTY      STAT   TIME COMMAND
 5298 ?        Sl     0:00 /opt/td-agent/embedded/bin/ruby /usr/sbin/td-agent --log /var/log/td-agent/td-agent.log --daemon /var/run/td-agent/td-agent.pid
 5301 ?        Sl     0:39 /opt/td-agent/embedded/bin/ruby /usr/sbin/td-agent --log /var/log/td-agent/td-agent.log --daemon /var/run/td-agent/td-agent.pid
```
How to identify the **supervisor** or **worker** process from above?

In the meanwhile, is the **monitor_agent** plugin necessary for monitoring? (I don't think)

Finally, what are best practices for monitoring fluentd? What else should be monitored except the two processes mentioned above?

Thanks.

Regards.

**Comment by sonots** [comment]
Use ps auxwwf
You can find parent-children relationships of processes. The parent is the
supervisor.

> best practices for monitoring fluentd
It is a difficult question because it depends on your usages of fluentd.
But, I monitor states of buffers (monitor_agent tells), number of messages
processing (flowcounter plugin tells), latency until processing messages
(my latency plugin is available), cpu usage per process (not in entire
host), memory usages.

Regards,
Naotoshi a.k.a. sonots

**Comment by papiveron** [comment]
Hi @sonots,

Thank you for your reply. 
 
Yes, for all linux standard metrics like cpu and memory usage I wrote scripts for that.

My question for fluentd specially, and your answers are helpful. I will have a look at your **latency** plugin and the others in order to build a complete fluentd monitoring  template.

Regards.

**Comment by papiveron** [comment]
Hi @sonots,

I took a look at your plugins, which seem really great. But I have some questions please:

- For the flow counter plugin : what is the real purpose of this plugin? In which case do you think we'll need to count messages processing?
And I noticed the @tagomoris flowcounter plugin can count specific field, and yours counts all fields. Are these counted messages the messages as they are writen in log files by applications? **e.g** a message can be a line of apache access log file for example. Right?
Also the first plugin has an option to specify file to write counts, but in yours you just say **in log file"", which log file is used? Or your plugin also allow to specify path the counter output file (I didn't the parameter in the list)? 
I ask all these questions because you said you write your own flowcounter plugin for simplicity and performance, which seems useful for in order to make choice.


- For the latency plugin, the purpose of plugin is really clear, and I have just two question.
 Taken from the README you have this :

```
latency: {"max":1.011,"avg":0.002","num":10}
```
where **max** and **avg** are the maximum and average latency, and **num** is the number of messages.
Thus I guess **max** and **avg** are expressed here in seconds. is that right? And **num** is which number of messages? Messages lost/blocked or what?
And once again how to specify the path to file for **lantency** plugin outputs

Thank a lot for all your attention.

Regards.

**Comment by sonots** [comment]
> For the flow counter plugin : what is the real purpose of this plugin?
The purpose is to count number of messages of processing. If a fluentd
deals lots of message, it is not rare that number of processing which a
process can deal without delays hits a peak even if CPU or memory is still
available. My criteria to increase number of fluentd processes usually
comes from number of messages processing rather than CPU or memory usages.
(But, it depends on usages of fluentd. I wanted to achieve realtime-ness,
but you may not).

>  but in yours you just say **in log file"", which log file is used?
Do you mean flowcounter-simple? It writes to fluentd log file.
flowcounter-simple was created for fluentd benchmark
https://github.com/fluent/fluentd-benchmark, so I do not think users use it
in production. It is simple, so lacks many features.

> Thus I guess *max* and *avg* are expressed here in seconds. is that
right?
Default is in minuites. You can configure with `unit` option

> And *num* is which number of messages? Messages lost/blocked or what?
num is just the number of messages processed in the time duration (unit
option), similar to `count` field of flowcounter plugin, used to compute
`avg`.

Regards,
Naotoshi a.k.a sonots


2015-08-19 19:48 GMT+09:00 Eugène NGONTANG <notifications@github.com>:

**Comment by papiveron** [comment]
Ah great @sonots 

> My criteria to increase number of fluentd processes usually comes from number of messages processing rather than CPU or memory usages.

Interesting. What do you mean by increase the number of fluentd processes?You mean running several **supervisor** and **worker**. You mean shard fluentd log processing within several fluentd instances ? Is this possible with fluentd?

Thanks.

**Comment by sonots** [comment]
Yes, I run multiple fluentd processes on multiple hosts. out_forward plugin
supports such architecture in round robin fashion.

Regards,
Naotoshi

**Comment by papiveron** [comment]
Ah yes I see, It's clear. I was thinking in a single machine.

**Comment by papiveron** [comment]
Hi @sonots ,

I have write my template for monitoring fluentd plugins, but it seems like the command :
```
curl http://host:24220/api/plugins.json
```
returns all installed plugin, which is too much and consume my monitoring engine resources. But I would like to monitor only the loaded plugins, means plugind loaded at **td-agent** startup.

How can achieve that? Thanks.

Regards

**Comment by sonots** [comment]
curl http://host:24220/api/plugins.json should return only loaded plugins.

My fluentd returns

```

$ curl http://localhost:24220/api/plugins.json
{"plugins":[{"plugin_id":"object:3fdc3d12b64c","plugin_category":"input","type":"monitor_agent","config":{"type":"monitor_agent"},"output_plugin":false,"retry_count":null},{"plugin_id":"object:3fdc3d1277b8","plugin_category":"input","type":"forward","config":{"type":"forward"},"output_plugin":false,"retry_count":null},{"plugin_id":"object:3fdc3d139328","plugin_category":"output","type":"stdout","config":{"type":"stdout"},"output_plugin":true,"retry_count":null}]}
```


for

```
<source>
  type monitor_agent
</source>

<source>
  type forward
</source>

<match **>
  type stdout
</match>
```

No any other plugins like out_tail, out_forward appear.


Regards,
Naotoshi a.k.a. sonots


2015-08-20 21:20 GMT+09:00 Eugène NGONTANG <notifications@github.com>:

**Comment by papiveron** [comment]
Yes @sonots , 

You're right.

Thanks
