### ISSUE TITLE
warning alert on Fluentd  Aggregator: failed to emit error="No such file or directory"

### ISSUE THREAD

**Issue by mperriere** [fluent/fluentd#741]
Hello, 
one of our Fluentd instance, acting as an aggregator and receiving other fluentd streaming is logging warning errors.

2015-12-08 11:15:19 +0100 [warn]: failed to emit error="No such file or directory @ sys_fail2 - (/opt/td-agent/buffer/..b5265fe9dabb0ca49.log, /opt/td-agent/buffer/..q5265fe9dabb0ca49.log)" pid=120814

This error is continous and i don't know why fluentd is looking for .log files that do not exist anymore.
Here is the aggregator configuration (output kinesis plugin only):

```aconf
<match apache.**>
  type kinesis                                               
  region eu-west-1                                             
  stream_name STR                                
  aws_key_id #####
  aws_sec_key #####
  random_partition_key true
  use_yajl true
Kinesis
  detach_process 40
  num_threads 2
  order_events false
  buffer_type file
  buffer_path /opt/td-agent/buffer/
  buffer_chunk_limit 32m
  buffer_queue_limit 1024
  flush_interval 5s
  retry_wait 20s
  retry_limit 15
  retry_wait 1s
  disable_retry_limit false
  log_level info
</match>
```

Fluentd version: 2.2.2-0.el7.x86_64
fluent-plugin-kinesis-0.4.0
OS: centos-7.-1
Is it a real issue, meaning that we have lost some data, or just a waring that can be discarded?
Thank You.

**Comment by repeatedly** [comment]
I assume `detach_process` and file buffer causes this problem.
Detached 2 processes share one buffer file accidentally and one process flushed and deleted its file.
After that, another process tries to write events file but not found.

I think data is not lost because one process flushes buffer without error.

For avoiding this issue, there are 2 approaches for now.
- Use memory buffer
- Use multiprocess plugin and setup different buffer_path and input plugins

**Comment by mperriere** [comment]
I'll have a look at multiprocess plugin to remove that warning.
Thank you for your help.

**Comment by repeatedly** [comment]
We will improve multi process support in the v0.14.
