### ISSUE TITLE
Add check and skip event option in in_forward

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd#774]
```
App - 1 -> fluentd-a - 2 -> fluentd-b
```

In the above topology, `2` transfer should be safe but `1` sometimes has a problem, e.g. client send an invalid event or something.
For debugging and stability, adding check and skip invalid event option is better.
This is helpful for identifying where is the cause of invalid event, 1 or 2? 

If set `skip_invalid_event true` in in_forward, in_forward checks received event like below.

```
if tag.is_a?(String)
if time.is_a?(Integer)
if record.is_a?(Hash)
```

If detect invalid event, in_forward logs information and skip its event.
This feature also prevents broken records are stored into buffer with PackedForward.

Enable this option on aggreagator may be hard because aggregator receives lots of events from lots of servers.
On the other hard, enable it on forwarder side is reasonable.

**Comment by sonots** [comment]
Adding `skip_invalid_event true` looks nice. 

What I doubt is `if record.is_a?(Hash)` might not be enough. I often see `ArgumentError: invalid byte sequence in UTF-8` on some plugins, and uses `String#scrub` to eliminate such invalid string. But, this depends on plugins, so, I can agree not to care of such error with `skip_invalid_event true`. What do you think?

**Comment by repeatedly** [comment]
> this depends on plugins,

Yeah. in_forward should check incoming event is Fluentd's event structure or not.
Others are application dependent so in_forward can't check such requirements.

**Comment by frsyuki** [comment]
I think in_forward is used for 2 different purposes:

* A) fluentd sends records to another fluentd
* B) clients or applications sends records to a fluentd

I think Validation is more important for B) because it's the entry point when fluentd receives new logs. In many cases, A) can omit validation since A) happens after B) if B) validates records.
And for B), clients which uses Message more likely have bugs. A) always uses PackedForward.

So, instead of #746, how about this idea?:

* If protocol is Message, check its structure by default (and no options to disable it). If the record is broken,
  * if `ignore_invalid_event` is false, raise an exception and close the socket.
  * if `ignore_invalid_event` is true, show warning, skip the record, and keep the socket.
* If protocol is Forward, check its structure by default (and no options to disable it). If at least one of the records is broken,
  * if `ignore_invalid_event` is false, purge ALL records, raise an exception, and close the socket.
  * if `ignore_invalid_event` is true, show warning, skip only broken records, and keep the socket.
* If protocol is PackedForward, don't check its structure by default. If `validate_forwarded_events` option is true, check the structure. If at least one of the records is broken,
  * if `ignore_invalid_event` is false, purge ALL records, raise an exception, and close the socket.
  * if `ignore_invalid_event` is true, skips broken records only (as much as possible) and keep the socket.

I think default value of `validate_forwarded_events` should be false for a performance reason.
But `ignore_invalid_event` can be true (I guess false is better, though).

**Comment by repeatedly** [comment]
@frsyuki Default validation is good idea but it can't be included in v0.12 changes. It may break protocol compatibility so it should be included in v0.14.

**Comment by repeatedly** [comment]
@frsyuki How about above my comment?

**Comment by repeatedly** [comment]
Does someone have any concern and suggest parameter name?
