### ISSUE TITLE
in_forward loses messages when restarting td-agent

### ISSUE THREAD

**Issue by static-max** [fluent/fluentd#801]
I'm using current td-agent with fluentd-0.12.19 on Ubuntu 14.04 LTS using offical td-agent apt repository.

I have a very simple setup: fluentd receives messages via in_forward and writes them to a file. I emit messages using fluent-logger-java at a rate of 10 messages/second, but the error also shows when the rate is higher. **When I restart fluentd while the java sender is still emitting, messages are dropped/lost at fluentd**. I debugged the java sender and the message that's dropped while restarting fluentd get re-emitted by the sender using its buffer. So the error must be on fluentd side.
How can this happen? I thought a simple restart should by handled by fluentd?! What if fluentd crashes hard in production? Or is the in_forward plugin the wrong way to go?

```
<source>
  type forward
</source>

<match mytags.**>
  @type file
  path /tmp/testfile
</match>
```

**Comment by repeatedly** [comment]
@komamitsu Could you check this?

**Comment by komamitsu** [comment]
Okay. I'll check it later.

**Comment by komamitsu** [comment]
@static-max 
I guess the followings occurred at that time.

1. Fluentd closed the accepted socket when the process was going to finish while fluent-logger-java kept sending messages
2. fluent-logger-java failed to send messages and stored them on the buffer (default 8KB) quietly
3. fluent-logger-java sent the buffered messages to Fluentd when it re-started

In this case, there are two possible causes.

a) In step 1, some messages sent from fluent-logger-java were stored in the OS's TCP buffer on Fluentd side. Calling fluent-logger-java's RawSocketSender#emit() succeeded since it received ACK from the TCP stack of Fluentd. But when the Fluentd process was going to finish, the messages were still buffered in the TCP buffer. As a result, the messages could be lost on Fluentd side.

b) In step 2, fluent-logger-java's send buffer could be full. As a result, some messages could be lost on fluent-logger-java side.

For a), Fluentd can do nothing against this problem without ACK response mode that guarantees at-least-once delivery. Most fluent-loggers don't support ACK response mode while https://github.com/komamitsu/fluency supports the mode. So you can resolve the issue with `fluency` (also it supports Fluentd failover.) But ACK response mode can lead duplicated message since it doesn't guarantees at-most-once.

For b), RawSocketSender#emit() returns false if the buffer is full and you can detect it. But the throughput is only 10rps and it's unlikely buffer was full at that time.

**Comment by static-max** [comment]
@komamitsu
I did not come across fluency and will give it a try, thanks for the advice.

For b) I can cleary say that the buffer wasn't full, I triple checked that.

**Comment by tagomoris** [comment]
This issue looks be solved by using at-least-once delivery with Fluency. Let me close.
